version: 2

before:
  hooks:
    - go test ./...
    - golangci-lint run
    - go mod tidy

builds:
  - id: default
    main: ./cmd/dot
    binary: dot
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -X main.builtBy=goreleaser
    flags:
      - -trimpath

archives:
  - id: archives-unix
    formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md
  
  - id: archives-windows
    formats:
      - zip
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'
      - '^style:'
      - Merge pull request
      - Merge branch
  groups:
    - title: Features
      regexp: '^feat.*'
      order: 0
    - title: Bug Fixes
      regexp: '^fix.*'
      order: 1
    - title: Performance Improvements
      regexp: '^perf.*'
      order: 2
    - title: Refactoring
      regexp: '^refactor.*'
      order: 3
    - title: Others
      order: 999

brews:
  - name: dot
    ids:
      - archives-unix
    repository:
      owner: jamesainslie
      name: homebrew-dot
      token: "{{ .Env.GITHUB_TOKEN }}"
    
    directory: Formula
    
    homepage: "https://github.com/yaklabco/dot"
    description: "Type-safe symbolic link manager for dotfiles"
    license: "MIT"
    
    install: |
      bin.install "dot"
    
    test: |
      system "#{bin}/dot", "--version"
      system "#{bin}/dot", "--help"
    
    caveats: |
      dot manages configuration files through symbolic links.
      
      Configuration file location (XDG Base Directory):
        $XDG_CONFIG_HOME/dot/config.yaml
        or ~/.config/dot/config.yaml
      
      Basic usage:
        dot manage <package>    # Install package
        dot status             # Show package status
        dot unmanage <package>  # Remove package
      
      Documentation: https://github.com/yaklabco/dot

release:
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## Release {{.Tag}}
    
    **Release Date**: {{.Date}}
    
    For detailed changes, see the [CHANGELOG](https://github.com/yaklabco/dot/blob/main/CHANGELOG.md).
  footer: |
    ## Installation
    
    ### Homebrew
    ```bash
    brew tap yaklabco/dot
    brew install dot
    ```
    
    ### Binary Download
    Download the appropriate binary for your platform from the assets below.
    
    ### Go Install
    ```bash
    go install github.com/yaklabco/dot/cmd/dot@{{.Tag}}
    ```
  name_template: "{{.ProjectName}} {{.Version}}"

